In [1]:
import numpy as np
import pandas as pd

In [2]:
#1. How likely is it that you roll doubles when rolling two dice?

first_die = np.random.choice([1, 2, 3, 4, 5, 6], size=100_000)
second_die = np.random.choice([1, 2, 3, 4, 5, 6], size=100_000)

first_die, second_die

(array([5, 6, 6, ..., 5, 3, 1]), array([1, 5, 6, ..., 5, 5, 2]))

In [3]:
(first_die == second_die).mean()

0.1661

In [4]:
#1 alternate sol:
n_simulations = nrows = 10**5
n_dice_rolled = ncols = 2

rolls = np.random.choice([1, 2, 3, 4, 5, 6], nrows * ncols).reshape(nrows, ncols)

df = pd.DataFrame(rolls)
df.head(5)

0  1
0  2  3
1  4  5
2  6  6
3  3  1
4  1  1

In [5]:
roll_doubles = (df[0] == df[1]).mean()
roll_doubles

0.16486

In [9]:
#2. If you flip 8 coins, what is the probability of getting exactly 3 heads? 

outcomes = ['heads', 'tails']
n_simulations = 100_000
n_trials = 8 #b/c 8 coins

flips = np.random.choice(outcomes, size=(n_simulations, n_trials))
(flips == 'heads')

array([[ True,  True, False, ..., False,  True,  True],
       [ True,  True, False, ..., False,  True,  True],
       [False,  True, False, ..., False, False, False],
       ...,
       [False,  True, False, ..., False, False, False],
       [False, False, False, ...,  True,  True,  True],
       [False,  True, False, ...,  True, False, False]])

In [11]:
sum_of_flips = (flips == 'heads').sum(axis=1)
sum_of_flips

array([5, 4, 3, ..., 1, 4, 4])

In [12]:
(sum_of_flips == 3).mean()

0.21833

In [60]:
#2a. What is the probability of getting more than 3 heads?
(sum_of_flips >= 3).mean() #cause more than 3 heads also is supposed to incl #3

#or (sum_of_flips > 2).mean()

0.85584

In [15]:
#3. There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. 
#Assuming that Codeup randomly selects an alumni to put on a billboard, 
#what are the odds that the two billboards I drive past both have data science students on them?

outcomes = ['webdev', 'ds']

drivebys = np.random.choice(outcomes, size = (100_000, 2), p = [0.75, 0.25])
(drivebys == 'ds')

array([[False, False],
       [False, False],
       [False, False],
       ...,
       [False,  True],
       [False, False],
       [False,  True]])

In [16]:
sum_of_drivebys = (drivebys == 'ds').sum(axis=1)
sum_of_drivebys

array([0, 0, 0, ..., 1, 0, 1])

In [17]:
(sum_of_drivebys == 2).mean()

0.06213

In [18]:
#3 alternate sol:
billboard = np.random.choice(['webdevelopment', 'datascience'], size = (100_000,2), p =(0.75, 0.25)).reshape(100_000, 2)
datascience_billboard = billboard ==['datascience', 'datascience']
(datascience_billboard.sum(axis =1)==2).mean()

0.06298

In [63]:
#3 alternate sol:
n_simulations = 1_000_000
n_trials = 2
data_science = 1
web_dev = 0
commutes = np.random.choice([data_science, web_dev], size=(n_simulations, n_trials), p=[0.25, 0.75])

(commutes.sum(axis=1) == 2).mean()

#[w,w,w,d] 
#3:1 are odds

0.062441

In [68]:
#4. Codeup students buy, on average, 3 poptart packages (+- 1.5) a day from the snack vending machine. 
#If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon?

poptarts = np.random.normal(3, 1.5, size = (100_000, 5)) 
poptarts                #3 b/c avg, #1.5 b/c std,    #5 b/c Friday

array([[ 1.28919407,  5.9185422 ,  2.63209191,  5.59616377,  3.02128439],
       [ 4.01606062, -0.20322166,  0.55748864,  2.53219754,  3.39160461],
       [ 2.20174783,  3.65091154,  3.90303131,  3.76973104,  4.62833822],
       ...,
       [ 4.7745034 ,  3.12882615,  3.57851624,  2.45064386,  4.9552325 ],
       [ 3.26698212,  3.20844945,  4.11742122,  2.05976174,  3.70096854],
       [ 0.79133631,  3.65742705,  1.37410462,  3.00215352, -0.67649057]])

In [69]:
weekly_demand = poptarts.sum(axis=1)
weekly_demand

array([18.45727635, 10.29412975, 18.15375994, ..., 18.88772215,
       16.35358307,  8.14853094])

In [75]:
(weekly_demand < 17).mean()

0.72281

In [73]:
#4 alternate sol:
pop_avg = 3
pop_std = 1.5
n_trials = 5
n_simulations = 1_000_000

simulated_consumed_poptarts = np.random.normal(pop_avg, pop_std, size=(n_simulations, n_trials))

(simulated_consumed_poptarts.sum(axis=1) < 17).mean()
#the prob that there will still be poptarts in the vending machine after 5 days is .72468

0.72468

In [24]:
#5. Compare Heights
#5a. Men have an average height of 178 cm and standard deviation of 8cm.
men = np.random.normal(178, 8, size=100_000)
men

array([186.28706139, 185.48033948, 169.25632252, ..., 161.35874455,
       188.46495135, 188.32022561])

In [26]:
#5b. Women have a mean of 170, sd = 6cm.
women = np.random.normal(170, 6, size=100_000)
women

array([163.85320156, 163.24111462, 172.87407106, ..., 171.94715829,
       167.75509262, 182.42545118])

In [27]:
#5c. If a man and woman are chosen at random, P(woman taller than man)?
(women > men).mean()

0.21365

In [76]:
#5 alternate sol:
men_avg = 178
men_std = 8
wmn_avg = 170
wmn_std = 6

s_men = np.random.normal(men_avg, men_std, 1_000_000)
s_wmn = np.random.normal(wmn_avg, wmn_std, 1_000_000)

(s_wmn > s_men).mean()

0.211653

In [97]:
#6a. When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. 
#What are the odds that after having 50 students download anaconda, no one has an installation issue?


#1/250 = 0.004 prob that we will have an anaconda failure

outcomes = [1, 0] #1=success, 0=failure
anaconda_50 = np.random.choice(outcomes, size = (100_000, 50), p=[0.996, 0.004])
(anaconda_50.sum(axis=1) == 50).mean()

0.81686

In [98]:
#6a alternate sol:
anaconda_install = np.random.choice(['fail', 'success'], size = (100_000, 50), p = (1/250, 249/250))
success_50 = ((anaconda_install == 'success').sum(axis=1) == 50).mean()
success_50

0.81652

In [99]:
#6b.  100 students?
outcomes = [1, 0] #1=success, 0=failure
anaconda_100 = np.random.choice(outcomes, size = (100_000, 100), p=[0.996, 0.004])
(anaconda_100.sum(axis=1) == 100).mean()

0.67032

In [100]:
#6b alternate sol
anaconda_install = np.random.choice(['fail', 'success'], size = (100_000, 100), p = (1/250, 249/250))
success_100 = ((anaconda_install == 'success').sum(axis=1) == 100).mean()
success_100

0.67247

In [85]:
#6c. What is the probability that we observe an installation issue within the first 150 students that download anaconda?
n_simulations = 1_000_000
n_trials = 150
conda_failure = 1
great_success = 0

attempted_class_installs = np.random.choice([conda_failure, great_success], size = (n_simulations, n_trials), p =[0.004, .996])
(attempted_class_installs.sum(axis=1) > 0).mean()


0.451782

In [87]:
#6c alternate sol:
anaconda_install = np.random.choice(['fail', 'success'], size = (100_000,150), p = (1/250, 249/250))
install_issue = ((anaconda_install == 'fail').sum(axis=1) > 0).mean()
install_issue

0.45098

In [94]:
#6c alternate sol:
anaconda_install = np.random.choice(['fail', 'success'], size = (100_000, 150), p = (1/250, 249/250))
install_issue = ((anaconda_install == 'success').sum(axis=1) < 150).mean()
install_issue

0.4548

In [102]:
#6d. How likely is it that 450 students all download anaconda without an issue?
outcomes = [1, 0] #1=success, 0=failure
anaconda_450 = np.random.choice(outcomes, size = (100_000, 450), p=[0.996, 0.004])
(anaconda_450.sum(axis=1) == 450).mean()

0.16461

In [101]:
#6d. 
anaconda_install = np.random.choice(['fail', 'success'], size = (100_000, 450), p = (1/250, 249/250))
success_450 = ((anaconda_install == 'success').sum(axis=1) == 450).mean()
success_450

0.16676

In [79]:
#7a. There's a 70% chance on any given day that there will be at least one food truck at Travis Park. 
#However, you haven't seen a food truck there in 3 days. 
#How unlikely is this?

#3 days of wk have passed, w/ 2 more left, assuming a reg bsns wk

n_simulations = 1_000_000
n_trials = 3 #1st 3 days of the week (#of wkdays. 3 days you haven't seen a truck)
food_truck = 1
no_truck = 0

lunch_days = np.random.choice([food_truck, no_truck], size=(n_simulations, n_trials), p=[0.7, 0.3])

(lunch_days.sum(axis=1)==0).mean()

0.026884

In [3]:
#7b. How likely is it that a food truck will show up sometime this week?

n_simulations = 1_000_000
n_trials = 2 #b/c 7 days versus 5 days (last 2 days)(presence of food truck is not dependent on whether or not one showed up the prev day)
food_truck =1
no_truck = 0

lunch_days = np.random.choice([food_truck, no_truck], size=(n_simulations, n_trials), p=[0.7, 0.3])
(lunch_days.sum(axis=1)>0).mean() #food truck showed up within those 2 days

0.910053

In [4]:
#7b. How likely is it that a food truck will show up sometime this week?
#another intepretation:
food_truck_outcomes =  [1,0]

food_truck_appearance_7 = np.random.choice(food_truck_outcomes,size=(n_simulations,7),p=[0.7,0.3])
(food_truck_appearance_7.sum(axis=1) > 0).mean()

0.999766

In [107]:
#8. If 23 people are in the same room, what are the odds that two of them share a birthday? 
birthday = np.random.randint(1, 366, (10_000, 23))
(pd.DataFrame(birthday).nunique(axis=1) < 23).mean()

0.4974

In [5]:
#alternate
bday_outcomes = list(range(1,366))
bdays = np.random.choice(bday_outcomes,size=(n_simulations,23))
bdays

array([[292, 185, 340, ..., 221,  99, 324],
       [154, 344, 267, ..., 133, 127, 246],
       [349, 359, 357, ..., 257, 324, 180],
       ...,
       [ 88,  59, 106, ..., 246,  69,  98],
       [117, 215, 282, ..., 238,  79, 135],
       [313, 193,  61, ..., 251, 176, 212]])

In [6]:
bdays_df = pd.DataFrame(bdays)
bdays_df.nunique(axis=1)

0         23
1         21
2         23
3         23
4         22
          ..
999995    21
999996    23
999997    22
999998    22
999999    23
Length: 1000000, dtype: int64

In [7]:
(bdays_df.nunique(axis=1) < 23).mean()

0.507254

In [106]:
#8. What if it's 20 people? 
birthday = np.random.randint(1, 366, (10_000, 20))
(pd.DataFrame(birthday).nunique(axis=1) < 20).mean()

0.4193

In [8]:
#alternate sol
bdays_20 = np.random.choice(bday_outcomes, size = (n_simulations, 20))
bdays_20_df = pd.DataFrame(bdays_20)
(bdays_20_df.nunique(axis=1) < 20).mean()

0.40994

In [108]:
#8 40?
birthday = np.random.randint(1, 366, (10_000, 40))
(pd.DataFrame(birthday).nunique(axis=1) < 40).mean()

0.8893

In [9]:
#alternate sol
bdays_40 = np.random.choice(bday_outcomes, size = (n_simulations, 40))
bdays_40_df = pd.DataFrame(bdays_40)
(bdays_40_df.nunique(axis=1) < 40).mean()

0.891475