In [1]:
import numpy as np
import pandas as pd

# How to run a simulation with Python/Numpy/Pandas
1. Figure out a way to represent our data
2. Create a matrix of random data, rows = simulations, columns = trial
    - Ex: rolling 2 dice 10,000 times means
        - rows = 10,000
        - col = 2 because we roll 2 dice each time
3. Apply an aggregate function, row-wise to get the results of the simulation
4. Apply a final aggregate to get our probability

# Generating Random Numbers with Numpy
The numpy.random module provides a number of functions for generating random numbers.

- np.random.choice: selects random options from a list
- np.random.uniform: generates numbers between a given lower and upper bound
- np.random.random: generates numbers between 0 and 1 (floats)
- np.random.randn: generates numbers from the standard normal distribution (bell curve)
- np.random.normal: generates numbers from a normal distribution with a specified mean and standard deviation

In [3]:
#what's the probability of flipping "heads" on a coin?

#flip a coin 100,000 times and figure out the prob of flipping "heads"

#to represent our data, make a list of outcomes:
outcomes = ["Heads", "Tails"]
number_of_simulations = 100_000

flips = np.random.choice(outcomes, size=number_of_simulations)
flips

array(['Tails', 'Heads', 'Tails', ..., 'Heads', 'Tails', 'Heads'],
      dtype='<U5')

In [5]:
(flips == "Heads")
#gives array of bools from the array above

array([False,  True, False, ...,  True, False,  True])

In [6]:
#After flipping 100 thousand coins, our experimental prob of flipping heads is:
(flips == "Heads").mean()

0.50092

In [8]:
outcomes = ["Heads", "Tails"]
number_of_trials = 10

flips = np.random.choice(outcomes, size=number_of_trials)
(flips == "Heads").mean()

0.8

In [9]:
outcomes = ["Heads", "Tails"]
number_of_trials = 100

flips = np.random.choice(outcomes, size=number_of_trials)
(flips == "Heads").mean()

0.39

In [10]:
outcomes = ["Heads", "Tails"]
number_of_trials = 1_000_000

flips = np.random.choice(outcomes, size=number_of_trials)
(flips == "Heads").mean()

0.500035

In [11]:
#Another example
#what is prob of rolling a 5 on a 6 sided die?

#stp 1, represent our data's outcomes
outcomes = [1, 2, 3, 4, 5, 6]

#stp 2, create the data
n_simulationss = 10_000

rolls=np.random.choice(outcomes, size=n_simulations)

#what are the chances we roll a 5? the probability
(rolls == 5).mean()

0.1736

In [12]:
#what is the probabiliyt we'll roll a 5 on a 6 sided die?
(rolls >= 5).mean()

0.3393

In [13]:
#what is the prob of rolling less than a 3 (but not including 3)
(rolls < 3).mean()

0.3323

In [14]:
#what are the chances we roll something other than 3
(rolls != 3).mean()

0.84

## roll 2 dice at once

1. Figure out a way to represent the data
2. Create a matrix of random data, rows = simultations, col = trials
3. Apply and aggregate row-wise to get the result of each simulation
4. Apply a final aggregate to get our probability

In [17]:
#what are the odds of rolling snake eyes on 2 dice

#stp 1: represent outcomes
outcomes = [1, 2, 3, 4, 5, 6]

#stp2: create a matrix of random data 
#rows = simulations
#cols = trial

#simulation = # of times we run the experiment
#trials = # of things in each experiment
n_simulations = 1_000_000
n_trials = 2 #b/c rolling 2 dice w/ each experiment

#size argument can set our simulation and trial size
rolls = np.random.choice(outcomes, size = (n_simulations, n_trials))
rolls

array([[3, 2],
       [5, 4],
       [3, 4],
       ...,
       [1, 6],
       [4, 4],
       [3, 3]])

In [18]:
#stp3: apply aggregate row-wise
rolls.sum(axis=1) #sum across the rows (axis=1)

array([5, 9, 7, ..., 7, 8, 6])

In [19]:
sum_of_rolls = rolls.sum(axis=1)
sum_of_rolls

array([5, 9, 7, ..., 7, 8, 6])

In [20]:
#axis = 0 means sum up the entire col
#if you don't put an axis, the default is 0
#rolls.sum(axis=0)

In [21]:
#stp4
(sum_of_rolls == 2).mean()
#adds up all the times that an experiment produces the sum of 2 (snake eyes)

0.027653

In [22]:
theoretical = 1/6 * 1/6
print(f"Our theoretical probability of rolling snake eyes is {theoretical}")

Our theoretical probability of rolling snake eyes is 0.027777777777777776


In [23]:
#what is the probability of rolling a 7 on two dice
#1+6, 2+5, 3+4, 4+3, 5+2, 6+1

#stp 1 represent outcomes
outcomes = [1, 2, 3, 4, 5, 6]

#stp 2 create matrix of random outcomes, simulations = rows, trials = cols
#size = (simulations, trials)
#size = (experiments, number_of_dice per experiment)
rolls = np.random.choice(outcomes, size = (10_000, 2))

#stp 3 apply row-wise aggregate
#axis=1 to apply sum to rows
sum_of_rolls = rolls.sum(axis=1)

(sum_of_rolls==7).mean()


0.1682

In [24]:
#possible sum outcomes from 2 dice
x = [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12] 

y = [(sum_of_rolls==n).mean() for n in sum_of_rolls]

In [26]:
sum_of_rolls[:10]

array([ 8, 11,  9,  4, 10,  5, 11,  8,  5, 10])

In [27]:
y[:10]

[0.1315,
 0.0552,
 0.1116,
 0.0893,
 0.0813,
 0.1109,
 0.0552,
 0.1315,
 0.1109,
 0.0813]

In [ ]:
# What are the experimental probabilities of rolling each sum
df = pd.DataFrame()
# possible sum outcomes from 2 dice
df["outcome"] = [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
# produce the probability of seeing each sum
y = [(sum_of_rolls == n).mean() for n in x]
# set the probability to its own column
df["probability"] = pd.Series(y)
print("Sum outcome of rolling 2 dice and the probability of seeing that outcome"s)
df

## Setting our own probabilities

In [30]:
#what's the probability of flipping "heads" on a coin?

#flip a coin 100,000 times and figure out the prob of flipping "heads"

#to represent our data, make a list of outcomes:
outcomes = ["Heads", "Tails"]

flips = np.random.choice(outcomes, size=(10_000, 1), p=[0.55, 0.45])

(flips == "Heads").mean()

0.5486

In [31]:
#what are the chances of flipping 2 heads in a row?
flips=np.random.choice(outcomes, size=(10_000, 2), p=[0.55, 0.45])
flips

array([['Tails', 'Heads'],
       ['Heads', 'Heads'],
       ['Heads', 'Heads'],
       ...,
       ['Tails', 'Tails'],
       ['Heads', 'Heads'],
       ['Tails', 'Heads']], dtype='<U5')

In [33]:
#it'll be a bit easier to check for 2 heads if the head = 1 and tail = 0
#might as well turn a binary in a binary

#lets say heads is 1 and tails is 0
outcomes = [1, 0]
flips = np.random.choice(outcomes, size=(100_000, 2), p=[0.55, 0.45])
flips

array([[0, 1],
       [1, 1],
       [1, 0],
       ...,
       [1, 1],
       [0, 0],
       [1, 0]])

In [35]:
num_of_heads = flips.sum(axis=1)
#axis=1 to sum across the rows, so we have as many sums as we had pairs of coin flips
len(num_of_heads)

100000

In [36]:
num_of_heads

array([1, 2, 1, ..., 2, 0, 1])

In [37]:
(num_of_heads == 2)
#bools line up w/ array from above

array([False,  True, False, ...,  True, False, False])

In [38]:
(num_of_heads == 2).mean()

0.30198

In [40]:
#what if this is a fair coin?
outcomes = [1,0]
flips = np.random.choice(outcomes, size=(100_000, 2))
num_of_heads = flips.sum(axis=1)
(num_of_heads == 2).mean()

0.25065

In [41]:
#theoretical probability of flipping 2 heads in a row
.5 * .5

0.25

In [42]:
# question mark gives docs for this function
np.random.normal?

In [44]:
#lets add some boolean logic to probabilities
#let's say we have an average of 0 and a standard dev of 20
numbers = np.random.randint(-50, 100, 100_000)
numbers

array([69, 47, 45, ..., 59, 41, 47])

In [45]:
#based on these simulations, what is the probability that any number is negative?
(numbers < 0).mean()

0.33286

In [46]:
#what is the probability a number is odd?
(numbers % 2 != 0)

array([ True,  True,  True, ...,  True,  True,  True])

In [50]:
#what is the probability of a number being BOTH odd AND negative?
is_negative = (numbers < 0)
is_odd = (numbers % 2 != 0)

(is_odd & is_negative).mean()

0.16668

In [51]:
#what is the probability of your number being even OR positive
is_even = (numbers % 2 == 0)
is_positive = (numbers > 0)
(is_even | is_positive).mean()

0.83332

In [52]:
#rolling 2 dice at a time, what is the prob of rolling an odd and then an even?

#stp1: represent the world in pandas/numpy
first_die = np.random.choice([1, 2, 3, 4, 5, 6], size = 100_000)
second_die = np.random.choice([1, 2, 3, 4, 5, 6], size = 100_000)

first_die, second_die

(array([6, 4, 1, ..., 2, 2, 2]), array([5, 1, 1, ..., 3, 6, 3]))

In [53]:
#we need to represent the results of the first die as an array of booleans
first_die % 2 != 0

array([False, False,  True, ..., False, False, False])

In [55]:
#give variable names and find first odd, second even
first_die_is_odd = (first_die %2 != 0)
second_die_is_even = (second_die %2 == 0)
first_odd_second_even = (first_die %2 != 0 & second_die_is_even)
first_odd_second_even

array([False, False,  True, ..., False, False, False])

In [56]:
first_odd_second_even.mean()

0.49832